version: "3.3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - esnet
  minio:
    image: minio/minio:RELEASE.2020-04-22T00-11-12Z
    volumes:
      - data:/data1
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: ${ACCESS_KEY}
      MINIO_SECRET_KEY: ${SECRET_KEY}
    command: server /data1
    healthcheck:
      disable: true
  app:
    build: .
    depends_on:
      - "es01"
    ports:
      - "80:80"
    networks:
      - esnet
    command: ["./wait-for-it.sh", "es01:9200", "-t", "60", "--", "bash", "entrypoint.sh"]

volumes:
  data:
    driver: local

networks:
  esnet:

  


