version: "3.3"
services:
  elk:
    image: sebp/elk
    volumes:
        - ./data:/usr/share/elasticsearch/data
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - esnet
  minio:
    image: minio/minio:RELEASE.2020-04-22T00-11-12Z
    volumes:
      - ./data:/data1
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: ${ACCESS_KEY}
      MINIO_SECRET_KEY: ${SECRET_KEY}
    command: server /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  app:
    build: .
    depends_on:
      - "elk"
    # ports:
    #   - "80:80"
    #   - "8501:8501"
    networks:
      - esnet
    command: ["./wait-for-it.sh", "elk:9200", "-t", "60", "--", "bash", "entrypoint.sh"]

volumes:
  data:
    driver: local

networks:
  esnet:
    driver: bridge
